version: "3"

services:
  devel:
    image: optic/devel
    build:
      context: docker/devel
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    #   - ./:/optic:delegated
    working_dir: /optic
    networks: [optic]

networks:
  optic:
    name: optic
    external: true
